# .streamlit/secrets.toml

# OpenAI API Key - (Pasting the key from your app.py)
openai_api_key = "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"

# Password for the Basic Login
test_password = "w7o5qhq88"
